QLBanHangMiniShop/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using QLBanHangMiniShop.Models;
using System.Web.Mvc;
using System.Web;
using Newtonsoft.Json;
using QLBanHangMiniShop.Class;

namespace QLBanHangMiniShop.Controllers
{
    
    public class CartsController : Controller
    {
        public class jsonMess
        {
            public string mess { get; set; }
            public int value { get; set; }
        }
        public class ItemCart
        {
            public int id { get; set; }
            public string hinhDaiDien { get; set; }
            public string tenSanPham { get; set; }
            public decimal gia { get; set; }
            public int soLuong { get; set; }
            public float giamGia { get; set; }
            public  decimal tongGia { get; set; }
        }
        [HttpGet]
        [ChildActionOnly]
        public ContentResult ReponseItemCart()
        {
            List<CartCookie> listIdProduct = new List<CartCookie>();
            listIdProduct = RequestCookie(listIdProduct, "CartCookie");
            return Content(listIdProduct.Count().ToString());
        }
        /// <summary>
        /// nhận id từ client cập nhật cookie mới danh sách id của sản phẩm
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]//trả về số lượng sản phẩm trong giỏ và thông báo
        public JsonResult UpdateItemCart(int id)
        {
            CartCookie newCookie = new CartCookie();
            jsonMess result = new jsonMess();
            
            // lấy cookie             
            List<CartCookie> listIdProduct = new List<CartCookie>();
            HttpCookie cartsCookie = HttpContext.Request.Cookies["CartCookie"];//lấy cookie từ client

            if (cartsCookie != null)//đã có cookie
            {
                string valueCookie = Server.UrlDecode(cartsCookie.Value);//dịch ngược cookie đã lấy
                listIdProduct = JsonConvert.DeserializeObject<List<CartCookie>>(valueCookie);//chuyển từ kiểu json sang list<int>
                //kiểm tra đã có id sản phẩm chưa
                if(listIdProduct.Where(c=>c.idProduct==id).Count()!=0)//đã có sản phẩm này thì tăng số lượng
                {
                    newCookie = listIdProduct.Where(c => c.idProduct == id).SingleOrDefault();
                    newCookie.total += 1;//tăng số lượng
                    listIdProduct.Remove(newCookie);
                    listIdProduct.Add(newCookie);
                    result.mess = "Đã cập nhật số lượng sản phẩm";
                    result.value = listIdProduct.Count();                   
                }
                else
                {
                    newCookie.total = 1;
                    newCookie.idProduct = id;
                    listIdProduct.Add(newCookie);
                    result.mess = "Đã thêm sản phẩm vào giỏ";
                    result.value = listIdProduct.Count();
                }    
                //tạo và gửi cookie
                string jsonItemCart = JsonConvert.SerializeObject(listIdProduct,Formatting.Indented);//chuyển list<int> thành chuỗi json
                HttpCookie cartCookie = new HttpCookie("CartCookie");
                cartCookie.Value = Server.UrlEncode(jsonItemCart);//mã hóa cookie
                HttpContext.Response.Cookies.Add(cartCookie);//ghi đè cookie mới lên cookie cũ
                return Json(result,JsonRequestBehavior.AllowGet);
            }
            else//nếu cookie chưa có 
            {
                newCookie.total = 1;
                newCookie.idProduct = id;
                listIdProduct.Add(newCookie);//thêm id mới vào cookie
                string jsonItemCart = JsonConvert.SerializeObject(listIdProduct, Formatting.Indented);//chuyển list<int> thành chuỗi json
                HttpCookie cartCookie = new HttpCookie("CartCookie");
                cartCookie.Value = Server.UrlEncode(jsonItemCart);//mã hóa cookie
                HttpContext.Response.Cookies.Add(cartCookie);//ghi đè cookie mới lên cookie cũ
                result.mess = "Đã thêm sản phẩm vào giỏ";
                result.value = 1;
                return Json(result, JsonRequestBehavior.AllowGet);
            }           
        }
        [HttpGet]
        public ActionResult Cart()
        {

            ViewBag.lstLoaiSP = Class.ListShop.GetListChungLoai();
            QLBanHangDbContext db = new QLBanHangDbContext();
            List<CartCookie> listIdProduct = new List<CartCookie>();
            listIdProduct = RequestCookie(listIdProduct, "CartCookie");
            List<ItemCart> listItemCart = new List<ItemCart>();
            decimal Subtotal = 0;
            float Discount = 0;
            foreach (var item in listIdProduct)
            {
                var product = db.HangHoas.Find(item.idProduct);
                ItemCart itemCart = new ItemCart {
                    id=product.ID,
                    hinhDaiDien = product.hinhDaiDien[0],
                    tenSanPham = product.Ten,
                    gia = (decimal)product.GiaBan,
                    soLuong = item.total,
                    tongGia = item.total * product.GiaBan
                                    
                };
                Subtotal+= (itemCart.gia * itemCart.soLuong);
                listItemCart.Add(itemCart);
            }
            ViewBag.Subtotal = Subtotal;
            ViewBag.Discount = Discount;
            ViewBag.Total = Subtotal - ((Subtotal / 100) * (decimal)Discount);

            //công cụ đếm số người đang online 
            SessionsAccess.SetSessionAccess(AccessMode.Visitor);
            return View(listItemCart);
        }
        private List<T>RequestCookie<T>(List<T> list,string cookieName )
        {           
            HttpCookie Cookie = HttpContext.Request.Cookies[cookieName];
            if (Cookie!=null)
            {
                string valueCookie = Server.UrlDecode(Cookie.Value);
                list = JsonConvert.DeserializeObject<List<T>>(valueCookie);
                return list;
            }       
            else
            {
                return list;
            }                    
        }
        public ActionResult CreateBill()///partialView
        {
            QLBanHangDbContext db = new QLBanHangDbContext();
            //tạo danh sách chưa cookie giỏ hàng
            List<CartCookie> listIdProduct = new List<CartCookie>();
            //lấy cookie
            listIdProduct = RequestCookie(listIdProduct, "CartCookie");
            decimal Total = 0;//tổng giá của giỏ hàng
            foreach(var item in listIdProduct)
            {
                Total += db.HangHoas.Find(item.idProduct).GiaBan * item.total;
            }
            ViewBag.Total = Total;
            return View();
        }
        [HttpPost]
        
        public ActionResult CreateBill(HoaDon hd)//chưa bắt lỗi và ngoại lệ
        {
            QLBanHangDbContext db = new QLBanHangDbContext();
            List<CartCookie> listIdProduct = new List<CartCookie>();
            listIdProduct = RequestCookie(listIdProduct, "CartCookie");
            foreach(var item in listIdProduct)
            {
                HoaDonChiTiet hdct = new HoaDonChiTiet();
                hdct.HoaDonID = hd.ID;
                hdct.HangHoaID = item.idProduct;
                hdct.SoLuong = item.total;
                hdct.DonGia= db.HangHoas.Find(item.idProduct).GiaBan;
                hdct.ThanhTien = item.total * db.HangHoas.Find(item.idProduct).GiaBan;
                hdct.HangHoa = db.HangHoas.Find(item.idProduct);
                hd.TongTien += hdct.ThanhTien;
                hd.HoaDonChiTiets.Add(hdct);                
            }
            hd.NgayDatHang = DateTime.Now;
            hd.TrangThai = "Chưa xác nhận";
            db.HoaDons.Add(hd);
            db.SaveChanges();
            var h = db.HoaDons.Where(x => x.ID == hd.ID).SingleOrDefault();
            if (Request.Cookies["CartCookie"] != null)
            {
                var infock = new HttpCookie("CartCookie");
                infock.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(infock);
            }
            return RedirectToAction("Cart");
        }
        [HttpPost]
        public ActionResult RemoveItemCart(int id)
        {
            CartCookie item = new CartCookie();
            jsonMess result = new jsonMess();

            // lấy cookie             
            List<CartCookie> listIdProduct = new List<CartCookie>();
            HttpCookie cartsCookie = HttpContext.Request.Cookies["CartCookie"];//lấy cookie từ client

            if (cartsCookie != null)//đã có cookie
            {
                string valueCookie = Server.UrlDecode(cartsCookie.Value);//dịch ngược cookie đã lấy
                listIdProduct = JsonConvert.DeserializeObject<List<CartCookie>>(valueCookie);//chuyển từ kiểu json sang list<int>
                //kiểm tra đã có id có tồn tại hay không
                if (listIdProduct.Where(c => c.idProduct == id).SingleOrDefault()!=null)//đã có sản phẩm này thì tăng số lượng
                {
                    item = listIdProduct.Where(c => c.idProduct == id).SingleOrDefault();
                  
                    listIdProduct.Remove(item);
                    result.mess = "Đã bỏ sản phẩm khỏi giỏ";
                    result.value = listIdProduct.Count();
                }
                else
                {
                    
                    result.mess = "Lỗi khi xóa sản phẩm";
                    result.value = listIdProduct.Count();
                }
                //tạo và gửi cookie
                string jsonItemCart = JsonConvert.SerializeObject(listIdProduct, Formatting.Indented);//chuyển list<int> thành chuỗi json
                HttpCookie cartCookie = new HttpCookie("CartCookie");
                cartCookie.Value = Server.UrlEncode(jsonItemCart);//mã hóa cookie

QLBanHangMiniShop/Views/Shared/HomeLayout/_IndexLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <title>DBWeb</title>
    <link rel="stylesheet" href="~/Content/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">

    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">

    <link rel="stylesheet" href="~/Content/css/aos.css">

    <link rel="stylesheet" href="~/Content/css/ionicons.min.css">

    <link rel="stylesheet" href="~/Content/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Content/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/Content/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <link href="~/Content/css/css/StyleIndex.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/style.css">

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Content/Admin/plugins/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/Content/js/Cart.js"></script>


    @RenderSection("ScriptsHeader", false)
    @RenderSection("Style", false)

</head>
<body class="goto-here" >

    <div class="py-1 bg-black">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex">
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span class="text">+84 332320859</span>
                        </div>
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                            <span class="text">ngocttu@gmail.com</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand hoverItem" href="#">Minishop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"> <a href="@Url.Content("~/Home/Index")" class="nav-link " style="color:#ff0000 !important ;font-weight:900"><span class="hoverItem">Home</span></a></li>
                    <li class="nav-item dropdown">
                        <a class=" nav-link dropdown-toggle " href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="hoverItem">Sản phẩm</span></a>

                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            @{List<ChungLoai> lstChungLoai = (List<ChungLoai>)ViewBag.lstLoaiSP;}
                            @foreach (ChungLoai item in lstChungLoai)
                            {
                                <a class="dropdown-item" href=@Url.Content("~/Shop/Index?CloaiSP="+item.ID)>
                                    @item.Ten
                                </a>
                            }
                        </div>

                    </li>

                    <li class="nav-item"><a href="#" class="nav-link"><span class="hoverItem">Blog</span></a></li>
                    <li class="nav-item cta cta-colored"><a href=@Url.Action("Cart","Carts") class="nav-link"><span class="icon-shopping_cart"></span><text id="cartMenu">@Html.Action("ReponseItemCart", "Carts")</text></a></li>

                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->
    @*cho phép chèn nội dung nếu muốn*@
    @RenderSection("HeroBanner", false)
    @*Nội dung thiết kế chính của view*@
    @RenderBody()
    @*cho phép chèn nội dung nếu muốn*@
    @RenderSection("Gallery", false)

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row">
                <div class="mouse">
                    <a href="#" class="mouse-icon">
                        <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                    </a>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Minishop</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Menu</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Shop</a></li>
                            <li><a href="#" class="py-2 d-block">About</a></li>
                            <li><a href="#" class="py-2 d-block">Journal</a></li>
                            <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ftco-footer-widget mb-4">

                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">201, 192 Trần Văn Dư, phường 13, Quận Tân Bình,TP.HCM</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+84 332320859</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">ngocttu1221999@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        &copy;
                        <script>document.write(new Date().getFullYear());</script> DBot |<br> (This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>)
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery.easing.1.3.js"></script>
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <script src="~/Content/js/jquery.stellar.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/aos.js"></script>
    <script src="~/Content/js/jquery.animateNumber.min.js"></script>
    <script src="~/Content/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/js/scrollax.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/js/PhanTrang.js"></script>


    

    @RenderSection("Scripts", false)

</body>
</html>